spring.application.name=task-manager
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/taskmanagement
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# JWT
spring.app.jwtSecret=G3hLt60szQf01XLGQ1PSc7KCKW7jHWiss4i_jhwbbOU
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookieName=taskmanager
#Email Configurations
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=taskmanager.rakhii@gmail.com
#spring.mail.password=ztbs xttk wdtt efuc
#spring.mail.properties.mail.smpt.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

